
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Le super blog!</title>
    <!--Appel fontawesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!--Appel bootsrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--Appel a la bibliotheque Jquery-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="crossorigin="anonymous"></script>
    <!-- on concatene une variable avec le chemin vers le css pour l'adapter en fonction de la page (index.php ou les views)-->
    <link rel="stylesheet" href=<?= $link."views/css/style.css"?> type="text/css" />
</head>

<body>
    <header>
        <div class="top-header">
            <p class="subtitle">Allo le monde ! </p>
            <p>Des news de l'infini et au-delà !</p>
            <img src=<?= $link."views/css/asset/buzeclair.png"?>>
            
            <nav class="menu-admin">
                <p><a href=<?=$link."./controllers/admin.php"?>> <i class="fas fa-cogs"></i>Administration</a></p>
            
                <?php if(isset($_SESSION['pseudoAdmin'])): ?>
                <p><a href=<?=$link."./controllers/deconnexion.php"?>>Déconnexion</a></p>
                <?php endif; ?>
            </nav>
            
        </div>
        
        
        <nav>
            <ul class='main-menu'>
                <li><a href=<?=$link."./index.php"?>><i class="fas fa-home"></i>Accueil</a></li>
            </ul>
        </nav>
    </header>
    
    <main>
    
    <!--PARTIE DYNAMIQUE-->
    
    <?php require $template.".phtml" ?>
    <!---->
    </main>
    
    <footer>
        <div class=" footer container">
        <small>Le footer du super blog</small>
            <i class="fab fa-facebook"></i>
            <i class="fab fa-twitter-square"></i>
            <p>Copyright, super blog 2021</p>
        </div>
    </footer>
    
    

    <script  src="<?=$link?>js/script.js"> </script>
</body>

</html>