<?php if($_SESSION['pseudoAdmin']): ?>
    <main>
        <section>
            <div class="container">
                <h2>Modifier un article</h2>
                
                <form class="form" method="post" action="../controllers/modif_article.php" enctype="multipart/form-data">
                    
                    <fieldset>
                        <legend>Article</legend>
                        <input type="hidden" name="id_article" value="<?= $idArticle ?>"/>  
                        
                        <div>
                            <label for="titre">Titre : </label>
                            <input type="text" name="titre" placeholder="Titre de l'article" value="<?= htmlspecialchars($articlePourModif['titre']) ?>"/>
                        </div>
                        
                        <div>
                            <label for="image">choisir une image : </label>
                            <input type="hidden" name="MAX_FILE_SIZE" value="300000" />
                            <input type="file" name="image" value="<?= htmlspecialchars($articlePourModif['image']) ?>" />
                        </div>
                        
                        
                        <div>
                            <label for="contenu">Article : </label>
                            <textarea type="text" name="contenu" cols="33" rows="10" placeholder="votre article ..."/><?= htmlspecialchars($articlePourModif['contenu']) ?></textarea>
                        </div>
                        
                        <div>
                            <button type="submit" name="enregistrer" >Enregistrer</button>
                            <button type="reset" name="annuler" >Annuler</button>
                            <!--<input class="form-btn" type="submit" name="enregistrer" value="Enregistrer"/>-->
                            <!--<input class="form-btn" type="reset" name="annuler" value="Annuler les modifications"/>-->
                        </div>
                        
                    </fieldset>    
                
                </form>
            </div>        
        </section>
    </main>
<?php else: ?>
    
<?php header('location:../controllers/admin.php') ?>

<?php endif; ?>