<?php if(isset($_SESSION['pseudoAdmin'])): ?>
    <main>
        
        <section>
            
            <div class="container" >
                
                <form class="form" method="POST" action="new_user.php" >
                    <h2>Ajouter un nouvel Utilisateur</h2>
                    
                    <div>
                        <label for="user">Pseudo : </label>
                        <input type="text" name="user-pseudo" placeholder="pseudo"/>
                    </div>
                    
                    <div>
                        <label for="user-pwd">Mot de passe : </label>
                        <input type="text" name="user-pwd" placeholder="mot de passe"/>
                    </div>
                    
                    <div>
                       <button type="submit" name="enregistrer">Enregistrer</button>
                    </div>
                    
                </form>
                
            </div>
        </section>
        
    </main>
<?php else: ?>
    <?php header('location:../controllers/admin.php'); ?>
<?php endif; ?>